/*
 *
 *    Copyright IBM Corp. 2023
 *
 *
 */

package com.ibm.cics.cip.bankliberty.datainterfaces;
import com.ibm.jzos.fields.*;

// Generated by IBM Record Generator for Java V3.0.2 Build 20221206-1121 on: Tue Feb 14 07:09:30 CST 2023

public class GetCompany {
	protected static CobolDatatypeFactory factory = new CobolDatatypeFactory();
	static { factory.setStringTrimDefault(false); } 

	/** <pre>
	 LINKAGE SECTION. </pre> */
	public static final int DFHCOMMAREA_len = 40; 

	/** <pre>
	 01 DFHCOMMAREA.
	     COPY GETCOMPY.
    *
    *
    *    Copyright IBM Corp. 2023
    *
    *
    *
	     03 GETCompanyOperation. </pre> */
	public static final int GETCOMPANYOPERATION_len = 40; 
	public static final int GETCOMPANYOPERATION_offset = factory.getOffset();

	/** <pre>
	     03 GETCompanyOperation. </pre> */
	protected static final StringField COMPANY_NAME = factory.getStringField(40);

	protected byte[] _byteBuffer;
	// Instance variables used to cache field values
	protected String companyName;


	public GetCompany (byte[] buffer) {
		this._byteBuffer = buffer;
	}

	public GetCompany () {
		this._byteBuffer = new byte[DFHCOMMAREA_len];
	}

	public byte[] getByteBuffer() {
		return _byteBuffer;
	}


	public String getCompanyName() {
		if (companyName == null) {
			companyName = COMPANY_NAME.getString(_byteBuffer);
		}
		return companyName;
	}

	public void setCompanyName(String companyName) {
		if (COMPANY_NAME.equals(this.companyName, companyName)) {
			return;
		}
		COMPANY_NAME.putString(companyName, _byteBuffer);
		this.companyName = companyName;
	}

}
