/*
 *
 *    Copyright IBM Corp. 2023
 *
 */
package com.ibm.cics.cip.bankliberty.datainterfaces;

import com.ibm.jzos.fields.*;

// Generated by com.ibm.jzos.recordgen.cobol.RecordClassGenerator on Wed Dec 14 10:38:47 GMT 2016

public class GetSortCode
{


	protected static CobolDatatypeFactory factory = new CobolDatatypeFactory();
	static
	{
		factory.setStringTrimDefault(false);
	}

	/**
	 * <pre>
	 01 COBOL-LANGUAGE-STRUCTURE.
	 * </pre>
	 */
	public static final int COBOL_LANGUAGE_STRUCTURE_LEN = 6;

	/**
	 * <pre>
	     03 GETSORTCODEOperation.
	 * </pre>
	 */
	public static final int GETSORTCODEOPERATION_LEN = 6;

	public static final int GETSORTCODEOPERATION_OFFSET = factory.getOffset();

	/**
	 * <pre>
	       06 SORTCODE pic xXXXXX.
	 * </pre>
	 */
	protected static StringField sortCode = factory.getStringField(6);

	protected byte[] byteBuffer;


	public GetSortCode(byte[] buffer)
	{
		this.byteBuffer = buffer;
	}


	public GetSortCode()
	{
		this.byteBuffer = new byte[COBOL_LANGUAGE_STRUCTURE_LEN];
	}


	public byte[] getByteBuffer()
	{
		return byteBuffer;
	}


	public String getSortcode()
	{
		return sortCode.getString(byteBuffer);
	}


	public void setSortcode(String sortcode)
	{
		sortCode.putString(sortcode, byteBuffer);
	}

}
