/*
 *
 *    Copyright IBM Corp. 2023
 *
 *
 */

package com.ibm.cics.cip.bankliberty.datainterfaces;
import com.ibm.jzos.fields.*;

// Generated by IBM Record Generator for Java V3.0.2 Build 20221206-1121 on: Tue Feb 14 07:11:44 CST 2023

public class GetSortCode {
	protected static CobolDatatypeFactory factory = new CobolDatatypeFactory();
	static { factory.setStringTrimDefault(false); } 

	/** <pre>
	 LINKAGE SECTION. </pre> */
	public static final int DFHCOMMAREA_LEN = 6; 

	/** <pre>
	 01 DFHCOMMAREA.
	     COPY GETSCODE.
    *
    *
    *    Copyright IBM Corp. 2023
    *
    *
    *
	     03 GETSORTCODEOperation. </pre> */
	public static final int GETSORTCODEOPERATION_LEN = 6; 
	public static final int GETSORTCODEOPERATION_OFFSET = factory.getOffset();

	/** <pre>
	     03 GETSORTCODEOperation. </pre> */
	protected static final StringField SORTCODE = factory.getStringField(6);

	protected byte[] byteBuffer;
	// Instance variables used to cache field values
	protected String sortcodeString;


	public GetSortCode (byte[] buffer) {
		this.byteBuffer = buffer;
	}

	public GetSortCode () {
		this.byteBuffer = new byte[DFHCOMMAREA_LEN];
	}

	public byte[] getByteBuffer() {
		return byteBuffer;
	}


	public String getSortcode() {
		if (sortcodeString == null) {
			sortcodeString = SORTCODE.getString(byteBuffer);
		}
		return sortcodeString;
	}

	public void setSortcode(String sortcode) {
		if (SORTCODE.equals(this.sortcodeString, sortcode)) {
			return;
		}
		SORTCODE.putString(sortcode, byteBuffer);
		this.sortcodeString = sortcode;
	}

}
