/*
 *
 *    Copyright IBM Corp. 2022
 *
 */
package com.ibm.cics.cip.bankliberty.datainterfaces;
import com.ibm.jzos.fields.*;

// Generated by IBM Record Generator for Java V3.0.0 Build 20170904-1704 on: Fri Oct 06 09:57:34 BST 2017


public class NewAccountNumber {

    static final String COPYRIGHT =
      "Copyright IBM Corp. 2022";


	protected static CobolDatatypeFactory factory = new CobolDatatypeFactory();
	static { factory.setStringTrimDefault(false); } 

	/** <pre>
	 01 COBOL-LANGUAGE-STRUCTURE. </pre> */
	public static final int COBOL_LANGUAGE_STRUCTURE_LEN = 11; 

	/** <pre>
	    03 NEWACCNO-FUNCTION  PIC X. </pre> */
	protected static final StringField NEWACCNO_FUNCTION = factory.getStringField(1);

	/** <pre>
	    88 NEWACCNO-FUNCTION-GETNEW VALUE 'G'. </pre> */
	public static final String NEWACCNO_FUNCTION_GETNEW = "G";

	/** <pre>
	    88 NEWACCNO-FUNCTION-ROLLBACK VALUE 'R'. </pre> */
	public static final String NEWACCNO_FUNCTION_ROLLBACK = "R";

	/** <pre>
	    88 NEWACCNO-FUNCTION-CURRENT VALUE 'C'. </pre> */
	public static final String NEWACCNO_FUNCTION_CURRENT = "C";

	/** <pre>
	    03 ACCOUNT-NUMBER                  PIC 9(8) DISPLAY. </pre> */
	protected static final ExternalDecimalAsIntField ACCOUNT_NUMBER = factory.getExternalDecimalAsIntField(8, false, false, false, false);

	/** <pre>
	    03 NEWACCNO-SUCCESS                    PIC X. </pre> */
	protected static final StringField NEWACCNO_SUCCESS = factory.getStringField(1);

	/** <pre>
	    03 NEWACCNO-FAIL-CODE                  PIC X. </pre> */
	protected static final StringField NEWACCNO_FAIL_CODE = factory.getStringField(1);

	protected byte[] _byteBuffer;
	// Instance variables used to cache field values
	protected String newaccnoFunction;
	protected Integer accountNumber;
	protected String newaccnoSuccess;
	protected String newaccnoFailCode;


	public NewAccountNumber (byte[] buffer) {
		this._byteBuffer = buffer;
	}

	public NewAccountNumber () {
		this._byteBuffer = new byte[COBOL_LANGUAGE_STRUCTURE_LEN];
	}

	public byte[] getByteBuffer() {
		return _byteBuffer;
	}


	public String getNewaccnoFunction() {
		if (newaccnoFunction == null) {
			newaccnoFunction = NEWACCNO_FUNCTION.getString(_byteBuffer);
		}
		return newaccnoFunction;
	}

	public void setNewaccnoFunction(String newaccnoFunction) {
		if (NEWACCNO_FUNCTION.equals(this.newaccnoFunction, newaccnoFunction)) {
			return;
		}
		NEWACCNO_FUNCTION.putString(newaccnoFunction, _byteBuffer);
		this.newaccnoFunction = newaccnoFunction;
	}

	public boolean isNewaccnoFunctionGetnew() {
		return getNewaccnoFunction().equals(NEWACCNO_FUNCTION_GETNEW);
	}

	public boolean isNewaccnoFunctionRollback() {
		return getNewaccnoFunction().equals(NEWACCNO_FUNCTION_ROLLBACK);
	}

	public boolean isNewaccnoFunctionCurrent() {
		return getNewaccnoFunction().equals(NEWACCNO_FUNCTION_CURRENT);
	}

	public int getAccountNumber() {
		if (accountNumber == null) {
			accountNumber = new Integer(ACCOUNT_NUMBER.getInt(_byteBuffer));
		}
		return accountNumber.intValue();
	}

	public void setAccountNumber(int accountNumber) {
		if (ACCOUNT_NUMBER.equals(this.accountNumber, accountNumber)) {
			return;
		}
		ACCOUNT_NUMBER.putInt(accountNumber, _byteBuffer);
		this.accountNumber = new Integer(accountNumber);
	}

	public String getNewaccnoSuccess() {
		if (newaccnoSuccess == null) {
			newaccnoSuccess = NEWACCNO_SUCCESS.getString(_byteBuffer);
		}
		return newaccnoSuccess;
	}

	public void setNewaccnoSuccess(String newaccnoSuccess) {
		if (NEWACCNO_SUCCESS.equals(this.newaccnoSuccess, newaccnoSuccess)) {
			return;
		}
		NEWACCNO_SUCCESS.putString(newaccnoSuccess, _byteBuffer);
		this.newaccnoSuccess = newaccnoSuccess;
	}

	public String getNewaccnoFailCode() {
		if (newaccnoFailCode == null) {
			newaccnoFailCode = NEWACCNO_FAIL_CODE.getString(_byteBuffer);
		}
		return newaccnoFailCode;
	}

	public void setNewaccnoFailCode(String newaccnoFailCode) {
		if (NEWACCNO_FAIL_CODE.equals(this.newaccnoFailCode, newaccnoFailCode)) {
			return;
		}
		NEWACCNO_FAIL_CODE.putString(newaccnoFailCode, _byteBuffer);
		this.newaccnoFailCode = newaccnoFailCode;
	}

}
