/*
 *
 *    Copyright IBM Corp. 2023
 *
 *
 */

package com.ibm.cics.cip.bankliberty.datainterfaces;
import com.ibm.jzos.fields.*;

// Generated by IBM Record Generator for Java V3.0.2 Build 20221206-1121 on: Tue Feb 14 07:25:07 CST 2023

public class NewAccountNumber {
	protected static CobolDatatypeFactory factory = new CobolDatatypeFactory();
	static { factory.setStringTrimDefault(false); }

	/** <pre>
	 01 COBOL-LANGUAGE-STRUCTURE. </pre> */
	public static final int COBOL_LANGUAGE_STRUCTURE_LEN = 11;

	/** <pre>
	     03 NEWACCNO-FUNCTION  PIC X. </pre> */
	protected static final StringField NEWACCNO_FUNCTION = factory.getStringField(1);

	/** <pre>
	     88 NEWACCNO-FUNCTION-GETNEW VALUE 'G'. </pre> */
	public static final String NEWACCNO_FUNCTION_GETNEW = "G";

	/** <pre>
	     88 NEWACCNO-FUNCTION-ROLLBACK VALUE 'R'. </pre> */
	public static final String NEWACCNO_FUNCTION_ROLLBACK = "R";

	/** <pre>
	     88 NEWACCNO-FUNCTION-CURRENT VALUE 'C'. </pre> */
	public static final String NEWACCNO_FUNCTION_CURRENT = "C";

	/** <pre>
	     03 ACCOUNT-NUMBER                  PIC 9(8) DISPLAY. </pre> */
	protected static final ExternalDecimalAsIntField ACCOUNT_NUMBER = factory.getExternalDecimalAsIntField(8, false, false, false, false);

	/** <pre>
	     03 NEWACCNO-SUCCESS                    PIC X. </pre> */
	protected static final StringField NEWACCNO_SUCCESS = factory.getStringField(1);

	/** <pre>
	     03 NEWACCNO-FAIL-CODE                  PIC X. </pre> */
	protected static final StringField NEWACCNO_FAIL_CODE = factory.getStringField(1);

	protected byte[] byteBuffer;
	// Instance variables used to cache field values
	protected String newaccnoFunction;
	protected int accountNumber;
	protected boolean accountNumberIsSet;
	protected String newaccnoSuccess;
	protected String newaccnoFailCode;


	public NewAccountNumber (byte[] buffer) {
		this.byteBuffer = buffer;
	}

	public NewAccountNumber () {
		this.byteBuffer = new byte[COBOL_LANGUAGE_STRUCTURE_LEN];
	}

	public byte[] getByteBuffer() {
		return byteBuffer;
	}


	public String getNewaccnoFunction() {
		if (newaccnoFunction == null) {
			newaccnoFunction = NEWACCNO_FUNCTION.getString(byteBuffer);
		}
		return newaccnoFunction;
	}

	public void setNewaccnoFunction(String newaccnoFunction) {
		if (NEWACCNO_FUNCTION.equals(this.newaccnoFunction, newaccnoFunction)) {
			return;
		}
		NEWACCNO_FUNCTION.putString(newaccnoFunction, byteBuffer);
		this.newaccnoFunction = newaccnoFunction;
	}

	public boolean isNewaccnoFunctionGetnew() {
		return getNewaccnoFunction().equals(NEWACCNO_FUNCTION_GETNEW);
	}

	public boolean isNewaccnoFunctionRollback() {
		return getNewaccnoFunction().equals(NEWACCNO_FUNCTION_ROLLBACK);
	}

	public boolean isNewaccnoFunctionCurrent() {
		return getNewaccnoFunction().equals(NEWACCNO_FUNCTION_CURRENT);
	}

	public int getAccountNumber() {
		if (!accountNumberIsSet) {
			accountNumber = ACCOUNT_NUMBER.getInt(byteBuffer);
			accountNumberIsSet = true;
		}
		return accountNumber;
	}

	public void setAccountNumber(int accountNumber) {
		if (accountNumberIsSet && ACCOUNT_NUMBER.equals(this.accountNumber, accountNumber)) {
			return;
		}
		ACCOUNT_NUMBER.putInt(accountNumber, byteBuffer);
		this.accountNumber = accountNumber;
		accountNumberIsSet = true;
	}

	public String getNewaccnoSuccess() {
		if (newaccnoSuccess == null) {
			newaccnoSuccess = NEWACCNO_SUCCESS.getString(byteBuffer);
		}
		return newaccnoSuccess;
	}

	public void setNewaccnoSuccess(String newaccnoSuccess) {
		if (NEWACCNO_SUCCESS.equals(this.newaccnoSuccess, newaccnoSuccess)) {
			return;
		}
		NEWACCNO_SUCCESS.putString(newaccnoSuccess, byteBuffer);
		this.newaccnoSuccess = newaccnoSuccess;
	}

	public String getNewaccnoFailCode() {
		if (newaccnoFailCode == null) {
			newaccnoFailCode = NEWACCNO_FAIL_CODE.getString(byteBuffer);
		}
		return newaccnoFailCode;
	}

	public void setNewaccnoFailCode(String newaccnoFailCode) {
		if (NEWACCNO_FAIL_CODE.equals(this.newaccnoFailCode, newaccnoFailCode)) {
			return;
		}
		NEWACCNO_FAIL_CODE.putString(newaccnoFailCode, byteBuffer);
		this.newaccnoFailCode = newaccnoFailCode;
	}

}
