plugins {
    id 'java'
    id 'war'
    id 'org.springframework.boot' version '3.5.11'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.ibm.cics.cip.bank'
version = '1.1'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    providedCompile 'com.ibm.jzos:ibm.jzos:4.0.0.0'
    
    implementation 'com.beust:jcommander:1.82'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.21.1'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    
    implementation 'ch.qos.logback:logback-classic:1.5.25'
    implementation 'ch.qos.logback:logback-core:1.5.25'
    
    implementation('io.netty:netty-codec-http2:4.1.129.Final') {
        exclude group: 'commons-logging', module: 'commons-logging'
    }
    implementation 'io.netty:netty-common:4.1.125.Final'
    implementation 'io.projectreactor.netty:reactor-netty-http:1.2.8'
    implementation 'io.projectreactor.netty:reactor-netty-core:1.2.8'
    implementation 'io.netty:netty-handler'
    implementation 'io.netty:netty-all'
    implementation 'io.netty:netty-codec-haproxy'
    implementation('io.netty:netty-codec-http:4.1.129.Final') {
        exclude group: 'commons-logging', module: 'commons-logging'
    }
    
    providedCompile 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'de.codecentric:spring-boot-admin-server:3.2.3'
    implementation 'org.thymeleaf:thymeleaf:3.1.2.RELEASE'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf:3.1.2'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-devtools:3.1.0'
    implementation 'org.springframework:spring-web:6.2.8'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.yaml:snakeyaml:2.0'
    
    providedCompile 'jakarta.validation:jakarta.validation-api:3.1.1'
    providedCompile 'jakarta.servlet:jakarta.servlet-api:5.0.0'
}